.PHONY: all

all: basic

basic:
	./ai.sh
	./arduino.sh
	./chrome.sh
	./cuda.sh
	./discord.sh
	./docker.sh
	./flutter.sh
	./latex.sh
	./lazygit.sh
	./lvim.sh
	./misc.sh
	./nice_to_have_programs.sh
	./opencv.sh
	./ros2.sh
	./terminal.sh
	./zsh.sh
	./thunderbird.sh
	./unity.sh
	./vm.sh
	./vpn.sh
	./vscode.sh
	./youtube.sh
	./zsh.sh

device_specific:
	./dell_laptop.sh
	./swap.sh
	./background.sh
