-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- ==================

-- KEYBINDINGS

-- ==================

local mod = "SUPER"

-- === Application Launchers ===

hl.bind(mod .. " + " .. "T", hl.dsp.exec_cmd("alacritty"))

hl.bind(mod .. " + " .. "E", hl.dsp.exec_cmd("nautilus"))

hl.bind(mod .. " + " .. "B", hl.dsp.exec_cmd("google-chrome-stable --ozone-platform=wayland"))

hl.bind(mod .. " + " .. "P", hl.dsp.exec_cmd("~/.config/hypr/scripts/kill-menu.sh"))

hl.bind(mod .. " + " .. "space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))

hl.bind(mod .. " + " .. "V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"))

hl.bind(mod .. " + " .. "comma", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"))

hl.bind(mod .. " + " .. "N", hl.dsp.exec_cmd("dms ipc call notifications toggle"))

hl.bind("SUPER" .. " + " .. "D", hl.dsp.exec_cmd("wayscriber --active"))

-- Scratchpad discord

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("~/.config/hypr/scripts/discord-scratchpad.sh"))

hl.window_rule({
    name  = "workspace_special_di",
    match = {
        match = "class ^(discord)$",
    },
    workspace = "special:discord silent",
})

-- Scratchpad Thunderbird

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exec_cmd("~/.config/hypr/scripts/mail-scratchpad.sh"))

hl.window_rule({
    name  = "workspace_special_ma",
    match = {
        match = "class org.mozilla.Thunderbird",
    },
    workspace = "special:mail silent",
})

-- Task Manager

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("~/.config/hypr/scripts/task-manager-scratchpad.sh"))

hl.window_rule({
    name  = "workspace_special_mi",
    match = {
        match = "class io.missioncenter.MissionCenter",
    },
    workspace = "special:missioncenter silent",
})

-- Calendar

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "C", hl.dsp.exec_cmd("~/.config/hypr/scripts/calendar.sh"))

hl.window_rule({
    name  = "workspace_special_ca",
    match = {
        match = "class org.gnome.Calendar",
    },
    workspace = "special:calendar silent",
})

-- Music -> Amberol

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Y", hl.dsp.exec_cmd("~/.config/hypr/scripts/music.sh"))

hl.window_rule({
    name  = "workspace_special_mu",
    match = {
        match = "class io.bassi.Amberol",
    },
    workspace = "special:music silent",
})

-- === Cheat sheet

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "Slash", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))

-- === Audio Controls ===

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 3"), { locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 3"), { locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("dms ipc call audio micmute"), { locked = true })

-- === Brightness Controls ===

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("dms ipc call brightness increment 5"), { locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5"), { locked = true })

-- === Window Management ===

hl.bind(mod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mod .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "F", hl.dsp.window.fullscreen())

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "T", hl.dsp.window.float())

hl.bind(mod .. " + " .. "W", hl.dsp.group.toggle())

-- === Focus Navigation ===

hl.bind(mod .. " + " .. "left", hl.dsp.focus({ direction = "left" }))

hl.bind(mod .. " + " .. "down", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + " .. "up", hl.dsp.focus({ direction = "up" }))

hl.bind(mod .. " + " .. "right", hl.dsp.focus({ direction = "right" }))

hl.bind(mod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))

hl.bind(mod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

hl.bind(mod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))

hl.bind(mod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))

-- === Window Movement ===

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "left", { direction = "l" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "down", { direction = "d" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "up", { direction = "u" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "right", { direction = "r" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "H", { direction = "l" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "J", { direction = "d" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "K", { direction = "u" })

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "L", { direction = "r" })

-- === Column Navigation ===

hl.bind(mod .. " + " .. "Home", hl.dsp.focus({ window = "first" }))

hl.bind(mod .. " + " .. "End", hl.dsp.focus({ window = "last" }))

-- === Monitor Navigation ===

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "left", hl.dsp.focus("l"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "right", hl.dsp.focus("r"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "H", hl.dsp.focus("l"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "J", hl.dsp.focus("d"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "K", hl.dsp.focus("u"))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.focus("r"))

-- === Move compelete workspace to Monitor ===

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mod + CTRL + SHIFT + left", hl.dsp.movecurrentworkspacetomonitor("l"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mod + CTRL + SHIFT + right", hl.dsp.movecurrentworkspacetomonitor("r"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mod + CTRL + SHIFT + up", hl.dsp.movecurrentworkspacetomonitor("u"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mod + CTRL + SHIFT + down", hl.dsp.movecurrentworkspacetomonitor("d"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mod + CTRL + SHIFT + H", hl.dsp.movecurrentworkspacetomonitor("l"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mod + CTRL + SHIFT + L", hl.dsp.movecurrentworkspacetomonitor("r"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mod + CTRL + SHIFT + K", hl.dsp.movecurrentworkspacetomonitor("u"))

-- TODO: manual review (unknown dispatcher: movecurrentworkspacetomonitor)
-- hl.bind("$mod + CTRL + SHIFT + J", hl.dsp.movecurrentworkspacetomonitor("d"))

-- === Workspace Navigation ===

hl.bind(mod .. " + " .. "Page_Down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mod .. " + " .. "Page_Up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + " .. "I", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mod .. " + " .. "U", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "down", hl.dsp.window.move({ direction = "e+1" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "up", hl.dsp.window.move({ direction = "e-1" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "I", hl.dsp.window.move({ direction = "e+1" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "U", hl.dsp.window.move({ direction = "e-1" }))

-- === Mouse Wheel Navigation ===

hl.bind(mod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))

hl.bind(mod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "mouse_down", hl.dsp.window.move({ direction = "e+1" }))

hl.bind(mod .. " + " .. "CTRL" .. " + " .. "mouse_up", hl.dsp.window.move({ direction = "e-1" }))

-- === Numbered Workspaces ===

hl.bind(mod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

-- === Move to Numbered Workspaces ===

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

-- === Column Management ===

hl.bind(mod .. " + " .. "bracketleft", hl.dsp.layout("preselect l"))

hl.bind(mod .. " + " .. "bracketright", hl.dsp.layout("preselect r"))

-- === Sizing & Layout ===

hl.bind(mod .. " + " .. "R", hl.dsp.layout("togglesplit"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + CTRL + F", hl.dsp.resizeactive("exact 100%"))

-- === Move/resize windows with mainMod + LMB/RMB and dragging ===

hl.bind(mod .. " + " .. "mouse:272", nil, { mouse = true })

hl.bind(mod .. " + " .. "mouse:273", hl.dsp.window.resize(nil), { mouse = true })

-- === Move/resize windows with mainMod + LMB/RMB and dragging ===

-- TODO: manual review (unknown dispatcher: Expand window left)
-- hl.bind("$mod + code:20", hl.dsp.Expand window left("resizeactive", "-100 0"))

-- TODO: manual review (unknown dispatcher: Shrink window left)
-- hl.bind("$mod + code:21", hl.dsp.Shrink window left("resizeactive", "100 0"))

-- === Manual Sizing ===

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + minus", hl.dsp.resizeactive("-5% 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + equal", hl.dsp.resizeactive("5% 0"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + SHIFT + minus", hl.dsp.resizeactive("0 -5%"))

-- TODO: manual review (unknown dispatcher: resizeactive)
-- hl.bind("$mod + SHIFT + equal", hl.dsp.resizeactive("0 5%"))

-- === Screenshots ===

hl.bind(mod .. " + " .. "S", hl.dsp.exec_cmd("dms screenshot"))

hl.bind("Print", hl.dsp.exec_cmd("dms screenshot"))

hl.bind(mod .. " + " .. "SHIFT" .. " + " .. "S", hl.dsp.exec_cmd("dms screenshot full"))

hl.bind("CTRL" .. " + " .. "Print", hl.dsp.exec_cmd("dms screenshot full"))

hl.bind("ALT" .. " + " .. "Print", hl.dsp.exec_cmd("dms screenshot window"))

-- === System Controls ===

hl.bind(mod .. " + " .. "Escape", hl.dsp.exec_cmd("dms ipc call powermenu toggle"))

hl.bind("CTRL" .. " + " .. "Escape", hl.dsp.exec_cmd("dms ipc call bar toggle index 0"))
