-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Hyprland Configuration

-- https://wiki.hypr.land/Configuring/

local binds = require("binds")
local plugins = require("plugins")

hl.env("SSH_AUTH_SOCK", "local_var_XDG_RUNTIME_DIR/ssh-agent.socket")

hl.env("DMS_DISABLE_MATUGEN", 1)

-- no theme generation from dms


-- Wallpaper



-- ==================

-- MONITOR CONFIG

-- ==================

-- monitor = eDP-2, 2560x1600@239.998993, 2560x0, 1, vrr, 1

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1.2,
})

-- unscale XWayland

hl.config({
    xwayland = {
        enabled = true,
        force_zero_scaling = true,
    },
})

-- ==================

-- STARTUP APPS

-- ==================



-- ==================

-- INPUT CONFIG

-- ==================

hl.config({
    input = {
        kb_layout = "us",
        numlock_by_default = true,
        kb_options = "compose:ralt",
    },
})

-- ==================

-- GENERAL LAYOUT

-- ==================

hl.config({
    general = {
        gaps_in = 0,
        gaps_out = 0,
        border_size = 2,
        -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
        -- col.inactive_border = rgba(0,0,0,0) # TODO: inactive border is transparent, even tho it shouldn't
        -- Set to true enable resizing windows by clicking and dragging on borders and gaps
        resize_on_border = true,
        -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
        col = {
            active_border = "rgb(8aadf4)",
        },
    },
})

-- ==================

-- DECORATION

-- ==================

hl.config({
    decoration = {
        rounding = 0,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 30,
            render_power = 5,
            offset = "0 5",
            color = "rgba(00000070)",
        },
    },
})

-- ==================

-- ANIMATIONS

-- ==================

hl.config({
    animations = {
        enabled = true,
    },
})

-- ==================

-- LAYOUTS

-- ==================

hl.config({
    dwindle = {
        preserve_split = true,
    },
})

hl.config({
    master = {
        mfact = 0.5,
    },
})

-- ==================

-- MISC

-- ==================

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        vrr = 1,
    },
})

-- source = . /dms/outputs.conf -> requires manual conversion
-- local outputs = require("outputs")
-- TODO: convert . /dms/outputs.conf to .lua and use require()

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload")
    hl.exec_cmd("dms run")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("awww img ~/.config/wallpapers/XPPeepo_M4x_Day.png")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
