setup:
  hint: "Base setup with all common dependencies"
  preparation-steps:
    - "./link.sh" # Link dotfiles
  packages:
    - aur-helpers
    - bazel
    - c++
    - dart
    - dev-tools
    - dotnet
    - flatpak
    - golang
    - haskell
    - homebrew
    - java
    - lua
    - node
    - oh-my-zsh
    - python
    - repositories
    - rust
    - zsh
    - neovim
    - cmake
    - meson
    - lazygit
    - lvim
    - keys
